### ISSUE TITLE
Release pimatic-homeduino

### ISSUE THREAD

**Issue by michbeck100** [pimatic/pimatic-homeduino#89]
It would be great if pimatic-homeduino 0.9.12 could be released. The last release is more than 2 years ago.
It seems that especially 0a6057bbbb72ea26bef98d7740c9da99a0e44793 brings node 8 compatibility, as homeduinojs uses serial port v4. See https://forum.pimatic.org/topic/4517/install-sqlite3-on-nodev8-problem/15 for example.

**Comment by michbeck100** [comment]
Now this issue gets relevant again since the change from 1861bd4ce20ce0a340b81749457dfe5b67b81846 add support for Node 10, too.

**Comment by mwittig** [comment]
Sure, it is matter of days now.

**Comment by akicker** [comment]
Unfortunately 0.9.12 does not work on may raspberrys - neiter on node 4 nor on node 8 or higher
I am using Raspberry Pi 3 B with 433 MHz transmitter and receiver (via gpio)
errors running pimatic.js:
[pimatic-homeduino] data: "hardware not supported"
[pimatic-homeduino] data: "garbage collected wiringX library"

**Comment by akicker** [comment]
Uups (0.9.13) & (0.9.14) not working :-( neither on node 4 nor on node 10 
errors running pimatic.js: 
Loading plugin: "pimatic-homeduino" (0.9.14) 
[pimatic] **Invalid or unexpected token**

**Comment by akicker** [comment]
Cool! 0.9.15 works perfect on node 4 up to 10 :-)

**Comment by mwittig** [comment]
@akicker Regarding your weather devices please, either file a new issue with more details or post at https://forum.pimatic.org/

I am closing this now as the original issue (Release pimatic-homeduino 0.9.12) had been resolved

**Comment by akicker** [comment]
Hi Marcus,

Got 0.9.15 working again on node 4 😊

It was a Plugins Settings problem:

I am using receiverPin: 16, transmitterPin: 12 (because the default pins are in use by a tft display)

this conflicts with the default value of dstSearchAddressPin: 12 even if enableDSTSensors is (default) set to No !!!

Solved by modifying the conflicting dstSearchAddressPin to any other unused pin :-) enableDSTSensors unchanged

On my Test-device using node 10 this conflict does not matter, did modify dstSearchAddressPin nevertheless in the same way as on node 4

Gruß aus Wien

August



 

 

Von: Marcus Wittig <notifications@github.com> 
Gesendet: Montag, 29. April 2019 18:03
An: pimatic/pimatic-homeduino <pimatic-homeduino@noreply.github.com>
Cc: Guss <a.kicker@aon.at>; Mention <mention@noreply.github.com>
Betreff: Re: [pimatic/pimatic-homeduino] Release pimatic-homeduino (#89)

 

@akicker <https://github.com/akicker>  Regarding your weather devices please, either file a new issue with more details or post at https://forum.pimatic.org/

I am closing this now as the original issue (Release pimatic-homeduino 0.9.12) had been resolved
