### ISSUE TITLE
Pi - do you need a Prefilter?

### ISSUE THREAD

**Issue by tstibbs** [pimatic/pimatic-homeduino#90]
The readme says that you can either run with an arduino or with "Raspberry Pi with ATTiny45 / 85 Prefilter", however the how to in the forum (https://forum.pimatic.org/topic/202/4-homeduino-433-mhz-sending-receiving-and-even-more) makes no mention of a Prefilter and suggests you can connect devices directly to the pi. One of both of these two places would benefit from clarification to explain when you would want to use a Prefilter?

**Comment by mwittig** [comment]
Yes, you can connect the devices directly to the pi. As stated in the "How-To" the direct connection has the disadvantage that "the cpu load will raise, since the Pi needs to do the RF computing all for itself. There were users reporting cpu loads of approx 40 to 50%, other users said it wouldn’t be that much." Besides this some users reported issues with noise which typically results in a low reception range. De-noising the power rail of the pi may solve this issue, however. 

General advice: Try the direct connection in your setup. If it does not produce sufficient results get a Arduino Nano for a few bucks. The pre-filter solution is not my advice in general unless you have experiences on the matter.
